# image: maven:3.6.3-adoptopenjdk-15 # default image 

pipelines:
  branches:
    master:
      - step:
          script:
            - "echo Starting the build for lazycow"
      - step:
          trigger: manual
          name: 'Create tarball and upload to transfer.sh'
          script:
            - apt-get install -y cowsay fortune || true
            - chmod +x ./scripts/release.sh && ./scripts/release.sh
