name: Pre-merge sanity checks

# only trigger it when a pull request is closed
on:
  push:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
    paths:
      - 'bin/**'
    
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Running checks
        run: |
          sudo apt-get install -y lolcat boxes
          chmod +x ./scripts/pre-merge-checks.sh && ./scripts/pre-merge-checks.sh
          chmod +x ./scripts/runtime-checks.sh && ./scripts/runtime-checks.sh
