name: Pre-merge sanity checks

# only trigger it when a pull request is opened
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Running checks
        run: |
          sudo apt-get install -y lolcat boxes
          chmod +x ./scripts/checks/pre-merge-checks.sh && ./scripts/checks/pre-merge-checks.sh
          chmod +x ./scripts/checks/runtime-checks.sh && ./scripts/checks/runtime-checks.sh
